name: explorer.nodex.one

on:
  push:
    branches:
      - master

jobs:
  commit:
    name: Chains merge
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout Latest
      uses: actions/checkout@v3   
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Fetch last commit
      shell: bash
      run: |
        echo "latestcommit=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Clone nodexplorer
      run: |
        git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/nodexemperor/nodexplorer

    - name: Setup config
      shell: bash
      run: |
        rm -rf nodexplorer/chains/*
        cp -rf chains/* nodexplorer/chains/

    - name: Setup logos
      run: cp -rf logos nodexplorer/public/

    - name: Update commit nodexplorer
      run: |
        cd nodexplorer
        git config --global user.name "Salman Wahib"
        git config --global user.email "hello@sxlmnwb.xyz"
        git add . && git commit -am "chains: merge with https://github.com/nodexemperor/explorer.nodex.one/commit/${{ env.latestcommit }}" -s && git push || echo "No changes to commit"
